### ISSUE TITLE
error fetching channel with new logged in user

### ISSUE THREAD

**Issue by wdavidw** [HN1997/Web-Server-Nodejs#1]
Once I loggin, the back-end crash with:

```
Key not found in database [users:david@adaltas.com]
/Users/david/projects/academy/webtech-projects/12/back-end/lib/db.js:43
          for(i=0;i<channel.emails.length;i++)

TypeError: Cannot read property 'length' of undefined
    at ReadStream.<anonymous> (/Users/david/projects/academy/webtech-projects/12/back-end/lib/db.js:43:36)
    at ReadStream.emit (events.js:315:20)
    at addChunk (/Users/david/projects/academy/webtech-projects/12/back-end/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/Users/david/projects/academy/webtech-projects/12/back-end/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at ReadStream.Readable.push (/Users/david/projects/academy/webtech-projects/12/back-end/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at /Users/david/projects/academy/webtech-projects/12/back-end/node_modules/level-iterator-stream/index.js:35:12
    at /Users/david/projects/academy/webtech-projects/12/back-end/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-iterator.js:33:14
    at /Users/david/projects/academy/webtech-projects/12/back-end/node_modules/encoding-down/index.js:140:5
    at /Users/david/projects/academy/webtech-projects/12/back-end/node_modules/abstract-leveldown/abstract-iterator.js:33:14
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

You must fix this because I can't browser the app otherwise

**Comment by HN1997** [comment]
Hello sir,
Sorry we didn't see your message, we are doing everything to fix this as soon as possible.

**Comment by HN1997** [comment]
It seems that you have tried to initialize the database with bin/init.
We specified in our README.md not to use this command because we made some modifications on the backend (we sould have probably deleted this file). 
The app is working perfectly for us without initializing the database, we have no errors and we can create channels.

**Comment by PierreC12033** [comment]
Hello sir,
We've looked into it and understood where the problem might reside .
Indeed as we wrote in the readme.md as you install the application you must not use the bin/init for the back-end before using bin/start.
We modify the structure of the database so the emails of each user using a channel would be stored inside the channel document in the database resulting in an array in the channel.emails variable. When you use the init file, channel.emails don't even exist resulting in the error. Hugo and me just tried it again and the error shows up only if we use the init file.

For a quick fix you can delete the db folder in the back-end and simply use bin/start.

If you need to install all the project again simply don't use the bin/init for the installation. 

Thank you
